version: '{build}'

image: Visual Studio 2017

environment:
  MYGET_API_KEY:
    secure: 78qy8e6pKfJlQV7RAG5tJOWegzXpjASkUs3aFdVBoPYA5gi6+mWdjbuAmNa5OQPe
  NUGET_API_KEY:
    secure: HrtMfG+bwaV8vPFGEc79kcNpq8DP2S2qGcI1eX4d5RnOt9I+HoPkhpFSJ6RGnEV/

assembly_info:
  patch: false

configuration:
  - Release

build_script:
  - ps: .\build.ps1

after_build:
  - ps: |
      $env:PATH = 'C:\msys64\usr\bin;' + $env:PATH
      Invoke-WebRequest -Uri 'https://codecov.io/bash' -OutFile codecov.sh
      bash codecov.sh -f "coverage.xml"

test: off

deploy: off
