version: '{build}'

image: Visual Studio 2019

environment:
  MYGET_API_KEY:
    secure: 78qy8e6pKfJlQV7RAG5tJOWegzXpjASkUs3aFdVBoPYA5gi6+mWdjbuAmNa5OQPe
  NUGET_API_KEY:
    secure: 2sTihXEDFVEQkGFRwSmYMvweUKW2Qphic3dqNJcdh8GZV5OHdDhIrbaVvlGEHLFS
  CODECOV_TOKEN:
    secure: EHy2Ls7M8sCfmxReWmbRxdkNkA/AqTTgg+6SCc1ww1JgHXCFmS/bpHJOzGt1VYAm

configuration:
  - Release

build_script:
  - cmd: dotnet tool restore && dotnet cake --bootstrap && dotnet cake

after_build:
  - pwsh: |
      $env:PATH = 'C:\msys64\usr\bin;' + $env:PATH
      Invoke-WebRequest -RetryIntervalSec 5 -MaximumRetryCount 5 -Uri 'https://codecov.io/bash' -OutFile codecov.sh
      bash codecov.sh -f "coverage/coverage.opencover.xml" -t $env:CODECOV_TOKEN
